### ISSUE TITLE
Add infos about each quark on website

### ISSUE THREAD

**Issue by capital-G** [supercollider-quarks/quarks#117]
Currently the website which is available under https://supercollider-quarks.github.io/quarks/ (which source code is in the [`gh-pages`](https://github.com/supercollider-quarks/quarks/tree/gh-pages) branch) does not contain information about the available quarks.
Even the GUI of SuperCollider does not show much beside the name as this information is not centralized but stored in each git repo and therefore requires a download of each quark.

I therefore decided to write a crawler which goes all git repos/quarks on a weekly basis and creates a json file which can be used for displaying information about quarks on a website.
As this is a static website there is no need for a server or database.

The source code is hosted at https://github.com/capital-G/quarks-web and the website is currently served via github-pages: https://capital-g.github.io/quarks-web/

It also adds the ability to check if the referenced repos are still available and also makes clear which repos are missing a quark file.

The question is if this should be integrated in the namespace of `supercollider-quarks`?

**Comment by dyfer** [comment]
Hi @capital-G 
I like it!
I'd be supportive of somehow integrating it with the quarks website. 
There's always a question of maintainability. We could consider either adding your repo to supercollider-quarks, or link to the page hosted on your GH to the Quarks page... what do others think?

**Comment by joslloand** [comment]
Hi All,

I've just had a look at [the page](https://capital-g.github.io/quarks-web/). It looks great! Yes, I think it would be a good idea to integrate it w/ the quarks web page.

My initial feeling is the thing to d would be to add it to supercollider-quarks.

**Comment by capital-G** [comment]
I think the maintainability is given as the workflow which updates the site runs itself every week https://github.com/capital-G/quarks-web/blob/main/.github/workflows/deploy.yaml
It runs w/o issues since May: https://github.com/capital-G/quarks-web/actions
For more informations take a look at https://github.com/capital-G/quarks-web/runs/8126303537?check_suite_focus=true under `Build JSON` and scroll down til sclang has been build and the script starts.

If this breaks the maintainers will be notified. The two things that can break are

file | what can go wrong
--- | ---
https://github.com/capital-G/quarks-web/blob/main/createJson.js | NPM can take libs/versions offline - in this case it needs a version bumping
calls -> https://github.com/capital-G/quarks-web/blob/main/quarkToJson.scd | I'd consider SC not as variable as Node these days but you never know. A broken `.quark` file can sometimes crash the interpreter so there is the possibility to "skip" quarks: https://github.com/capital-G/quarks-web/blob/12233b4e47cac8574b85433071a05d8775483d59/createJson.js#L12-L14

The whole containering stuff is solid, maybe needs an version bumping in a few years in case the Node image goes offline.
The rest are NPM files and the Vue frontend (which essentially boils down to https://github.com/capital-G/quarks-web/blob/main/src/components/QuarkSearch.vue ).
It is esay to reproduce the steps locally in case of an extensive error.

I wanted to solely use `node` for parsing of the Quark files but as these can contain functions and else so I actually employed a `sclang` into the container - sclang then translates the quark key/values to JSON key/values which then are used by the Vue frontend to display the available Quarks.

The current website (https://supercollider-quarks.github.io/quarks/) is actually just a GH pages template which displays the information shown in https://github.com/supercollider-quarks/quarks/blob/master/README.md

Any next steps or missing steps? :)

**Comment by dyfer** [comment]
Just wanted to say that I still think it would be great to add this to "official" SC web resources. I don't have the time resources to look into this myself at the moment.

While I do acknowledge @capital-G 's proposed system runs reliably, it is using many technologies that most active sc devs are not that familiar or comfortable with. At the same time, even if that is the case, I can see adopting this approach if there's an agreement to do so, since it's not critical to SC development (i.e. if it breaks, the quarks list won't get updated anymore, but nothing else would be affected).

I can see a few ways to go about it:
1. add it to the [supercollider-quarks website](https://supercollider-quarks.github.io/quarks/) (but is it possible to integrate it with the current website deployment? or the existing information there would need to be added to the proposed design)
  - btw I noticed that page seems not to be linked from the main website... or anywhere else really
2. create a new github website in the supercollider-quarks organization and linked from the main website
3. add a link to existing page in @capital-G 's repo as an "unofficial" but perfectly functional list of quarks 

`2.` is probably easier to set up than `1.`, but results in two pages dedicated to quarks. `3.` might not look as "polished", but would be the easiest to implement right away.

**Comment by capital-G** [comment]
Option 4: If there would be an official SC domain it would be possible to create a sub-url, e.g. <https://quarks.supercollider.org> which then [could serve the website from any repo via gh-pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site), preferably if it would be forked/donated to the sc-quarks namespace.

---

Regarding option 1: the website is simply a gh-pages template of the README.md, so I think while the information of the README is relevant it adds no real value.

**Comment by capital-G** [comment]
To give an update on this - I ditched the static website in favor of a "real" package index for quarks which uses the data from this repository, available under https://baryon.supercollider.online/ - for more information see https://scsynth.org/t/baryon-package-index-for-quarks/8450/ 

It could be linked in the repository here but as it is not about replacing the current website anymore I think this can be closed.
